### ISSUE TITLE
Create Recipe Index Presentational Component DUE: 10/26

### ISSUE THREAD

**Issue by bdberm** [bdberm/recipes#24]

**Comment by mikeboan** [comment]
Mostly only styling comments since everything seems to be functioning well:

- [ ] times new roman is very 90's. maybe look in to what font NYT uses?
- [ ] NYT has a big featured recipe image before the rest of the recipes. Can you implement something similar?
- [ ] hover shadows are less nice than the NYT ones. Don't be afraid of lifting the CSS directly from NYT for small things like that.

**Comment by mikeboan** [comment]
Also maybe add infinite scroll as a bonus feature?

**Comment by bdberm** [comment]
@mikeboan I'm for sure going to look into alternate fonts this weekend. I want to do the big splash/hero feature but pushed it to 11/2 as I want to make sure to start workig on/ shipping the interactive features inadvance. 

Will do on the hover shadows, I went a little overboard. I'll add infiniet scroll issue as bonus
